### ISSUE TITLE
3. checking and extracting info from ANOVA model

### ISSUE THREAD

**Issue by carmzh** [kel-github/PSY2R#51]
Ideal workflow:    
1) User define ANOVA: mod <- ez_aov()  
2) Define list of within contrast and/or between contrast
3) State method = "post-hoc"

**a) how many ways to define anova in R,   
b) how do you get df info from the model object,   
c) write function for checking contrast vector are correct length**

Function workflow:   
- {does the user want between, within, or between by within (multiply all between x within contrast vectors), or pairwise} to scale? or not to scale?
- check contrast vector are correct length using df from the model (Issue 3c: write function for this)
- create contrast() tables as required
- compute critical constants (cc)
- CIS

**Comment by garner-code** [comment]
Decided to rely on emmeans for #1
